name: Deploy
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
    - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
      with:
        node-version: '18.4.0'
        cache: 'yarn'
    - run: yarn install
    - run: yarn build
    - uses: peaceiris/actions-gh-pages@64b46b4226a4a12da2239ba3ea5aa73e3163c75b # v3.9.1
      if: github.event_name != 'pull_request'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        destination_dir: ./docs
